### ISSUE TITLE
Unable to implement code

### ISSUE THREAD

**Issue by arjuna87** [bwobbones/fullcalendar5-rightclick#1]
Hi, I would really like to be able to implement the right click hack you've kindly provided for my project, but struggling to understand how you implement the below code.  I have used npm to install and imported the dateclicking and interactionplugin, but I have no clue where to insert the const myinteractionPlugin... code or the data().. code? Any help much appreciated.

`Use a javascript proxy to patch in the change

import DateClicking from '@bwobbones/fullcalendar5-rightclick'
import interactionPlugin from '@fullcalendar/interaction'

const myInteractionPlugin = new Proxy(interactionPlugin, {
  get(target, prop, receiver) {
    if (prop === 'componentInteractions') {
      target.componentInteractions[0] = DateClicking
    }
    return Reflect.get(...arguments)
  }
});

Use the myInteractionPlugin instead of the interactionPlugin

data() {
    return {
      calendarOptions: {
        plugins: [myInteractionPlugin]
      }
    }
}
`

**Comment by bwobbones** [comment]
Hey @arjuna87, the code isn't too different from what they show on the [dateClick page](https://fullcalendar.io/docs/dateClick) already:

```
import { Calendar } from '@fullcalendar/core';
import interactionPlugin from '@fullcalendar/interaction';
...
let calendar = new Calendar(calendarEl, {
  plugins: [ interactionPlugin ],
  ...
  dateClick: function(info) {
    alert('Clicked on: ' + info.dateStr);
    alert('Coordinates: ' + info.jsEvent.pageX + ',' + info.jsEvent.pageY);
    alert('Current view: ' + info.view.type);
    // change the day's background color just for fun
    info.dayEl.style.backgroundColor = 'red';
  }
});
```

Just import the hack before the interaction plugin put the proxy in the middle:

```
import { Calendar } from '@fullcalendar/core';
import DateClicking from '@bwobbones/fullcalendar5-rightclick'
import interactionPlugin from '@fullcalendar/interaction'
...

const myInteractionPlugin = new Proxy(interactionPlugin, {
  get(target, prop, receiver) {
    if (prop === 'componentInteractions') {
      target.componentInteractions[0] = DateClicking
    }
    return Reflect.get(...arguments)
  }
});

let calendar = new Calendar(calendarEl, {
  plugins: [ myInteractionPlugin ],
  ...
  dateClick: function(info) {
    alert('Clicked on: ' + info.dateStr);
    alert('Coordinates: ' + info.jsEvent.pageX + ',' + info.jsEvent.pageY);
    alert('Current view: ' + info.view.type);
    // change the day's background color just for fun
    info.dayEl.style.backgroundColor = 'red';
  }
});
```

Make sense?
