### ISSUE TITLE
Use in Angular (v15)

### ISSUE THREAD

**Issue by certifirm** [bwobbones/fullcalendar5-rightclick#4]
How to use in angular?  

I tried but I can not do work the code in the example.

Any idea how to use this plugin?

**Comment by bwobbones** [comment]
@certifirm if you post some code, I can try and help?

**Comment by certifirm** [comment]
Well, this code is not working in angular. 

`
const myInteractionPlugin = new Proxy(interactionPlugin, {
  get(target, prop, receiver) {
    if (prop === 'componentInteractions') {
      target.componentInteractions[0] = DateClicking
    }
    return Reflect.get(...arguments)
  }
});
`

I have not found any info about create a Proxy function in Angular/Typescript.  And the reflect has types error.

**Comment by bwobbones** [comment]
So the important part is this one:

```
data() {
    return {
      calendarOptions: {
        plugins: [myInteractionPlugin]
      }
    }
}
```

That code is definitely vue specific and you'd need to replace it.  The code snippet you pinned is just a variable that you need to include in your plugin list, replacing [interationPlugin].

Looking at the fullcalendar docs, it looks like you do it like this?

```
import { Component } from '@angular/core';
import { CalendarOptions } from '@fullcalendar/core'; // useful for typechecking
import dayGridPlugin from '@fullcalendar/daygrid';
import interactionPlugin from '@fullcalendar/interaction'

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {

  const myInteractionPlugin = new Proxy(interactionPlugin, {
    get(target, prop, receiver) {
      if (prop === 'componentInteractions') {
        target.componentInteractions[0] = DateClicking
      }
      return Reflect.get(...arguments)
    }
  });

  calendarOptions: CalendarOptions = {
    initialView: 'dayGridMonth',
    plugins: [dayGridPlugin, myInteractionPlugin]
  };
}
```

But take that with a pinch of salt, I haven't used Angular in years.  If you get it working, put the code snippet in here and I'll update the README?

**Comment by certifirm** [comment]
<img width="457" alt="Captura de pantalla 2023-03-21 a las 8 45 37" src="https://user-images.githubusercontent.com/7561881/226544698-6e45f04b-842a-46a5-8ceb-d1d4c2e389d0.png">

Some errors:

In DateClicking -> Cannot find name 'DateClicking'.ts(2304)

In ...arguments -> A spread argument must either have a tuple type or be passed to a rest parameter.ts(2556)

I think that both of them are related with typescript definitions.

**Comment by bwobbones** [comment]
Ah yes, I don't use typescript.  Feel free to submit a `.d.ts` file!
